export const FETCH_BETS_REQUEST = 'FETCH_BETS_REQUEST';
export const FETCH_BETS_ERROR = 'FETCH_BETS_ERROR';
export const FETCH_BETS_SUCCESS = 'FETCH_BETS_SUCCESS';

export const POST_BETS_REQUEST = 'POST_BETS_REQUEST';
export const POST_BETS_ERROR = 'POST_BETS_ERROR';
export const POST_BETS_SUCCESS = 'POST_BETS_SUCCESS';

export const ADD_TO_MYBETS = 'ADD_TO_MYBETS';
export const REMOVE_FROM_MYBETS = 'REMOVE_FROM_MYBETS';

export const INCREMENT_STAKE = 'INCREMENT_STAKE';
export const DECREMENT_STAKE = 'DECREMENT_STAKE';

export const CLOSE_RECIEPT = 'CLOSE_RECIEPT';
